name: flutter_kpl_vip
description: Flutter app for kpl news
version: 1.0.0+7
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^2.1.0
  shared_preferences: ^0.5.3+1
  cached_network_image: ^0.8.0
  keyboard_actions: ^2.1.1
  json_annotation: ^2.4.0
  flutter_easyrefresh: ^2.0.3
  oktoast: ^2.1.9
  event_bus: ^1.1.0
  flutter_swiper : ^1.1.6
  webview_flutter: ^0.3.10+4
  url_launcher: ^5.1.2
  cupertino_icons: ^0.1.2
  package_info: ^0.4.0+6
  device_info: ^0.4.0+2
  flutter_screenutil: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/tabbar/
    - assets/images/recommend/
    - assets/images/testCard/
    - assets/images/level/
    - assets/images/answer/
    - assets/data/
